replicaCount: 2
image:
  repository: registry.example.com/paymentapp
  tag: latest
service:
  type: ClusterIP
  port: 8080
env:
  spring:
    datasource:
      url: jdbc:mysql://mysql:3306/paymentdb
      username: payment
      password: payment_pass
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
persistence:
  enabled: true
  size: 1Gi
