apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paymentapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://git.example.com/your-org/bank-payments.git'
    targetRevision: HEAD
    path: charts/paymentapp
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: paymentapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
